### ISSUE TITLE
Create dbt projects for MetricFlow Integration Test

### ISSUE THREAD

**Issue by Jstein77** [dbt-labs/metricflow#569]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing metricflow functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

MetricFlow uses a semantic manifest generated from a dbt project to build a semantic graph. We want to replicate this pattern as part of our integration tests, to provide end to end test coverage.

At a high level, this looks like creating a dbt project for each test tables we create in Metricflow.  Each project will have a profile for each supported SQL dialect, and connect to the platform using the appropriate adapter. 

Currently, we create test tables on the fly, and build a semantic graph using the old spec i.e `sql_table: my_test_table`. This pattern doesn’t represent how MetricFlow will actually build a semantic graph. 

We can approach adding dbt projects to to our integration tests in phases.

**Phase 1:**

Let's create a proof of concept. In this phase, we will test initializing a dbt project and an adapter. We can use the same structure that dbt-core uses for adapter testing to create a profile and spin up dbt projects. In core integration tests, a new dbt project is spun up and torn down for each test case.

First we need to create a profile. We can leverage a similar format to what’s used in [[dbt-bigquery](https://github.com/dbt-labs/dbt-bigquery/blob/389aceeff8e8e699c04d132c2c5b7af4c514c22c/tests/conftest.py)](https://github.com/dbt-labs/dbt-bigquery/blob/389aceeff8e8e699c04d132c2c5b7af4c514c22c/tests/conftest.py)  to create the profile, and use the profile to replace the SQLClient currently used for tests. An example implementation of a BigQuery profile is below:

```python
#GH repo path: dbt-labs/dbt-bigquery/tests/conftest.py
def service_account_target():
    credentials_json_str = os.getenv("BIGQUERY_TEST_SERVICE_ACCOUNT_JSON").replace("'", "")
    credentials = json.loads(credentials_json_str)
    project_id = credentials.get("project_id")
    return {
        "type": "bigquery",
        "method": "service-account-json",
        "threads": 1,
        "job_retries": 2,
        "project": project_id,
        "keyfile_json": credentials,
        # following 3 for python model
        "dataproc_region": os.getenv("DATAPROC_REGION"),
        "dataproc_cluster_name": os.getenv(
            "DATAPROC_CLUSTER_NAME"
        ),  # only needed for cluster submission method
        "gcs_bucket": os.getenv("GCS_BUCKET"),
    }
```

Next, we actually need to run the dbt project. There is a helper function called `run_dbt()` in [[dbt/core/dbt/tests/util.py](https://github.com/dbt-labs/dbt-core/blob/dc35f56baa6876e6381b46f9b99b45f29d58f857/core/dbt/tests/util.py#L28)](https://github.com/dbt-labs/dbt-core/blob/dc35f56baa6876e6381b46f9b99b45f29d58f857/core/dbt/tests/util.py#L28) that provides a clean way to run dbt projects using dbt_runner. An example of how this is implemented is below:

```python
from dbt.tests.util import run_dbt
class TestIncrementalModel(BaseIncrementalModelConfig):
    def test_incremental_model_succeeds(self, project):
        results = run_dbt(["run"])
        assert len(results) == 1
        results = run_dbt(["run"])
        assert len(results) == 1
```

The main change in Phase 1 is swapping out Metricflow’s built-in SQLClients for dbt adapters and to test running a dbt project. From here we can start migrating test table fixtures incrementally.

**Phase 2:**

Now that we have the skeleton working, we can start refactoring our tests to build tables from dbt projects. For this phase we need to:

- Replace the functions that create test tables, like `create_simple_model_tables()`, to instead run dbt projects.
- Generate a semantic manifest from these projects.
- Update the model_yaml fixtures to use the new spec and reference dbt models.

Open Questions?

- How smart is dbt runner? Ideally we would only run the models if test data has changed, otherwise we would just compile the project.

### Describe alternatives you've considered

Keeping the old testing framework.

### Who will this benefit?

MetricFlow developers. 

### Are you interested in contributing this feature?

I'm interested in pairing on this!
