### ISSUE TITLE
[SEM-353] Source time spine data externally

### ISSUE THREAD

**Issue by tlento** [dbt-labs/metricflow#591]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing metricflow functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

The current time spine dataset MetricFlow uses for managing cumulative and derived metric offset time windows is internally managed. This means MetricFlow runs introspective queries to ensure the time spine table exists and creates and populates the table on the fly if it is not in place. This forces MetricFlow to issue multiple queries during query the query planning phase, and requires things like table locks on create in case other queries might be running concurrently.

In order to simplify this process and make MetricFlow's time spine support more configurable with respect to date ranges and granularity support, we are going to remove this logic and make the time spine data set an input dependency much like the underlying tables/views powering each semantic model. Steps:

- [ ] dbt-labs/metricflow#592
- [ ] dbt-labs/dbt-semantic-interfaces#86
- [ ] dbt-labs/metricflow#594
- [ ] dbt-labs/metricflow#595
- [ ] dbt-labs/metricflow#596

### Describe alternatives you've considered

*No response*

### Who will this benefit?

*No response*

### Are you interested in contributing this feature?

*No response*

### Anything else?

*No response*

<sub>From [SyncLinear.com](https://synclinear.com) | [SL-353](https://linear.app/dbt-labs/issue/SL-353/source-time-spine-data-externally)</sub>
